version: '3.8'

services:
  # -----------------------------
  # MongoDB (optional)
  # -----------------------------
  mongo:
    image: mongo
    container_name: mongo-nest-project-2
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    ports:
      - '27019:27017'
    volumes:
      - mongo-data:/data/db

  # -----------------------------
  # Kafka placeholder (ไม่สร้าง Kafka ใหม่)
  # -----------------------------
  # kafka:
  #   image: alpine
  #   container_name: kafka-placeholder
  #   command: ["sh", "-c", "sleep infinity"]

  # -----------------------------
  # Consumer (NestJS)
  # -----------------------------
  # consumer:
  #   image: node:18-alpine
  #   container_name: consumer
  #   working_dir: /app
  #   # command: sh -c "npm install && npm run start:dev"
  #   # ติดตั้ง pnpm แล้วรัน
  #   command: sh -c "corepack enable && pnpm install && pnpm run start:dev"
  #   volumes:
  #     - ./:/app
  #     - /app/node_modules
  #   env_file:
  #     - .env
  #   ports:
  #     - "3002:3002"
  #   # depends_on:
  #   #   - kafka

  # consumer:
  #   image: node:18-alpine
  #   container_name: consumer
  #   working_dir: /app
  #   command: sh -c "corepack enable && pnpm install --store /pnpm-store && pnpm run start:dev"
  #   volumes:
  #     - ./:/app
  #     - pnpm-store:/pnpm-store   # ใช้ volume แยกสำหรับ pnpm store
  #   env_file:
  #     - .env
  #   ports:
  #     - "3002:3002"

volumes:
  mongo-data:
    driver: local
